[4] Remove Lander from Copyright and author
ros-realtime/rtwg_documentation pull request #21
Opened 2021-05-01 09:44 UTC by LanderU

Related #4 

Signed-off-by: LanderU <lander.usategui@gmail.com>

2021-05-01 09:45 UTC, LanderU commented
![image](https://user-images.githubusercontent.com/11192915/116778527-b84d4f00-aa72-11eb-9788-173e6c911911.png)

2021-05-01 12:06 UTC, razr approved these changes

2021-05-02 07:03 UTC, carlossvg requested changes
NIT: I would say " ROS 2 Real-Time Working Group"

2021-05-02 07:19 UTC, LanderU commented
@carlossvg, thanks! Done, ready for a second review.

2021-05-02 09:37 UTC, carlossvg approved these changes

2021-05-02 12:32 UTC, merged